### ISSUE TITLE
Adapt *+json media type handling to allow passthrough

### ISSUE THREAD

**Issue by rgbkrk** [nteract/commutable#50]
Because of how we do our processing of multiline strings (and as a consequence of the nbformat), arrays in `application/json` mime bundles are not treated as direct JSON. We need to make sure to allow Arrays at the top level.

In the past, we left this alone because Arrays on this mimetype were allowed in the past as arrays of multiline strings (double encoded JSON...)

**Comment by rgbkrk** [comment]
Upstream issue: https://github.com/jupyter/nbformat/issues/57

**Comment by rgbkrk** [comment]
@aleury This is that "harder" problem to solve in `commutable` to handle arrays on `application/json` and other JSON mimetypes. They currently have to deal with the ramifications of jupyter/nbformat#57, but I think we can pass through raw arrays as JSON here.

If you're interested, I can outline some approaches. You may end up having a better time tackling #51. Either way, I realize this code base is a bit hairier to approach. :smile:

**Comment by aleury** [comment]
I'd love to work on this. I've been meaning to take a deep dive into this project. Any pointers for more background info or approaches are most welcome! 😄

**Comment by rgbkrk** [comment]
Background: the notebook format splits long string fields that would normally appear like this:

```
source: "import IPython\nimport IPython.display\nIPython.display.HTML('<h1>hey</h1>')\n"
```

into "multiline-string-arrays":

```
source: [
  "import IPython\n",
  "import IPython.display\n",
  "IPython.display.HTML('<h1>hey</h1>')\n"
]
```

This is primarily there to make diffing notebooks with `git` much easier to work with.

When this notebook is loaded into memory, these multi-line strings need to be regular strings. For fields like code, html snippets, etc. it works pretty well to assume that when you see an array of strings you can combine them up into one.

_However_, now that `application/.*+json` can be a raw JSON object (no more double encoding), we have to tread carefully.

**Comment by rgbkrk** [comment]
Some relevant functions to look at:

* [`cleanMultiline`](https://github.com/nteract/commutable/blob/fc2d00f3c7c44639b7e2271656dd2198f8fb3505/src/cleaning.ts#L11)
* [`cleanMultilineNotebook`](https://github.com/nteract/commutable/blob/fc2d00f3c7c44639b7e2271656dd2198f8fb3505/src/cleaning.ts#L86-L88)

The flow of this recursive cleaning function for output data:

```
cleanMultilineNotebook
  -> processCells
    -> processCell
      -> processOutputs
        -> processOutputData
          -> cleanMultiline
```

I personally think the approach should be to special case `output` data that has keys that end in `json`, likely as part of [`processOutputData`](https://github.com/nteract/commutable/blob/fc2d00f3c7c44639b7e2271656dd2198f8fb3505/src/cleaning.ts#L43).

The reason I mentioned #51 though is that all this cleaning with Immutable.js, while pure, is also really slow since we're doing so many little operations. I encourage you to push us towards something clean and maintainable.

**Comment by rgbkrk** [comment]
All done in the `@nteract/commutable` library!
