### ISSUE TITLE
Markdown cell compatibility with jupyter

### ISSUE THREAD

**Issue by lgeiger** [nteract/commutable#52]
Consider a notebook created in nteract with one executed markdown cell containing 
```
1. Test
```

I get the following error if I open it with jupyter notebook:
```
Notebook Validation failed: Additional properties are not allowed ('outputExpanded' was unexpected):
{
 "metadata": {},
 "outputExpanded": false,
 "source": "1. Test",
 "cell_type": "markdown"
}
```

**Comment by lgeiger** [comment]
Oops sorry for the noise I wasn't using the latest master of nteract. It is fixed already.

**Comment by rgbkrk** [comment]
Seems we should make a release soon because of this!

/cc @captainsafia
